//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;


namespace AssemblyCSharp
{
  public static class Constants
  {
    public static List<float> slots = new List<float>{-6.2f, -5.2f,-4.2f,-3.2f,-2.2f,-1.2f,-0.2f,0.8f,1.8f,2.8f,3.8f,4.8f,5.8f};
  }
}

