//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Colors = ColorUtils.Colors;
namespace AssemblyCSharp
{
  
  public class BackgroundShift : GameEvent
  {    
    public Colors color;
    
    public BackgroundShift (Colors color, int delay):base(delay)
    {
      this.color = color;
    }
  }
}

