//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
  public class Boss : GameEvent
  {
    
    public Vector3 position;
    public int bossId;
    
    public Boss (Vector3 pos, int bossId, int delay):base(delay)
    {
      this.position = pos;
      this.bossId = bossId;
    }
  }
}

