//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
  public class Spawn
  {
    
    public Vector3 position;
    public ColorUtils.Colors color;
    public bool shielded;
    public bool rotated;
    
    public Spawn (Vector3 pos, ColorUtils.Colors color, bool shielded, bool rotated)
    {
      this.position = pos;
      this.color = color;      
      this.shielded = shielded;
      this.rotated = rotated;
    }
  }
}

